name: tests

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  schedule:
  # Runs at 6:10am UTC on Monday
    - cron: '10 6 * * 1'
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2

  manifest:
    name: Check Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/check_manifest@v2

  test:
    needs: [linting, manifest]
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run all supported Python versions on linux
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
        #Include one windows and two macOS (intel based and arm based) runs
        include:
        - os: macos-13
          python-version: "3.12"
        - os: macos-latest
          python-version: "3.12"
        - os: windows-latest
          python-version: "3.12"

    steps:
      - name: Cache brainglobe directory
        uses: actions/cache@v4
        with:
          path: | # ensure we don't cache any interrupted atlas download and extraction, if e.g. we cancel the workflow manually
            ~/.cache/pooch
            !~/.brainglobe/atlas.tar.gz
          key: brainglobe
      # these libraries enable testing on Qt on linux
      - uses: pyvista/setup-headless-display-action@v2
        with:
          qt: true

      # Run tests
      - uses: neuroinformatics-unit/actions/test@v2
        with:
          python-version: ${{ matrix.python-version }}
          secret-codecov-token: ${{ secrets.CODECOV_TOKEN }}

  on-failure:
    name: Notify slack on scheduled failure
    needs: [test]
#    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
        - uses: ravsamhq/notify-slack-action@v2
          if: always()
          with:
            status: ${{ github.event.workflow_run.conclusion }}
            notification_title: " ${{github.event.workflow_run.name}} - ${{github.event.workflow_run.conclusion}} on ${{github.event.workflow_run.head_branch}} - <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
            message_format: ":fire: *${{github.event.workflow_run.name}}* ${{github.event.workflow_run.conclusion}} in <${{github.server_url}}/${{github.repository}}/${{github.event.workflow_run.head_branch}}|${{github.repository}}>"
            footer: "Linked Repo <${{github.server_url}}/${{github.repository}}|${{github.repository}}> | <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}|View Failure>"
#            notify_when: "failure"
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFYBOT_WEBHOOOK_URL }}

  build_sdist_wheels:
    name: Build source distribution
    needs: [test]
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: neuroinformatics-unit/actions/build_sdist_wheels@v2


  upload_all:
    name: Publish build distributions
    needs: [build_sdist_wheels]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.TWINE_API_KEY }}
